In [1]:
import pandas as pd
import numpy as np

In [2]:
#Assign the Data(Excel File) to the Dataset
dataset = pd.read_csv("salary.csv")

In [3]:
dataset

yrs  salary
0     1   69640
1     2   58001
2     3   65787
3     4   80408
4     5   78675
5     6   52227
6     7   73500
7     8   64486
8     9   66967
9    10   74105
10   11   73440
11   12   88542
12   13   83610
13   14   79216
14   15   84438
15   16   85336
16   17   98940
17   18   83948
18   19   91130
19   20   81459
20   21   66470
21   22  100536
22   23  104644
23   24   90578
24   25  122697
25   26   87456
26   27  104457
27   28  104128
28   29  123327
29   30  124693

In [4]:
# Assign the dataset data to the "ind" Variable
ind = dataset[['yrs']]
ind
# Assign the dataset data to the "dep" Variable
dep = dataset [['salary']]
dep

salary
0    69640
1    58001
2    65787
3    80408
4    78675
5    52227
6    73500
7    64486
8    66967
9    74105
10   73440
11   88542
12   83610
13   79216
14   84438
15   85336
16   98940
17   83948
18   91130
19   81459
20   66470
21  100536
22  104644
23   90578
24  122697
25   87456
26  104457
27  104128
28  123327
29  124693

In [5]:
#Importing the Train test slpit function from the sklearn library
from sklearn.model_selection import train_test_split

In [6]:
#Assigning the ind and dep data to the (training test function variables) and the test data to 30%
x_train,x_test,y_train,y_test = train_test_split(ind,dep,test_size=0.30,random_state=0)

#importing the Liner REgression function from the sklearn
from sklearn.linear_model import LinearRegression

#Assigning the Liner Regression Class to the variable as "reg"
reg=LinearRegression()

# Fitting Function,  Fitting training set input and training set output data to the regression 
reg.fit(x_train, y_train)

LinearRegression()

In [18]:
# Now the regression coefficient is assigned to the weight variable
weight=reg.coef_

In [20]:
weight

array([[1502.40998755]])

In [22]:
# Now the regression intercept is assigned to the weight variable
bais=reg.intercept_

In [24]:
bais

array([60456.2297005])

In [28]:
# Assigning the Predit Value to the Variable (Cross Check Varaible)  
y_pred=reg.predict(x_test)

In [30]:
#importing the Librabry r2_Score from sklearn
from sklearn.metrics import r2_score

#calcuating the r_score value from y_test and y_predit
r_score=r2_score(y_test,y_pred)

In [32]:
r_score

0.6742721072752127

In [34]:
# Importing the Function "Pickle" to save our model in file
import pickle

# Assigning the File name to save our model vida variable "filename"
filename="fin_model_liner.sav"


In [36]:
# Saving our model in file in Binary format "Write binary"
pickle.dump(reg,open(filename,'wb'))

In [42]:
# Loading our Model from File "Read Binary"
loaded_model=pickle.load(open("fin_model_liner.sav",'rb'))

# Testing the model in realtime
result=loaded_model.predict([[28]])

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [46]:
result

array([[102523.70935186]])